import type { Metadata } from "next";
import { Hanken_Grotesk } from 'next/font/google'
import "./globals.css";

import Navbar from "@/components/navbar";
import Particles from "@/components/ui/particles";

const font = Hanken_Grotesk({
  subsets: ['latin'],
  display: 'swap'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className} antialiased bg-background text-text`}
      >
        <Particles
          className='fixed top-0 w-full h-full left-0 -z-10'
          quantity={140}
          ease={80}
          color="#dffbe5"
          refresh
        />
        <Navbar />
        {children}
        <div className="h-screen"></div>
      </body>
    </html>
  );
}
